### PR TITLE
Fix corner case where fractional currency token (without decimal digits) absorbs dot in dotExpression rule

### PR DESCRIPTION
**Pull request by aaronhurst-google**
Found an example of this when integrating 2.12.0.

Also cleaned up some unrelated linter issues.

### CODE REVIEW

**Comment by nawforce** [comment]
Thanks Aaron, I pushed out a 2.12.1 with a quick fix for this earlier but didn't get changes checked in, I have put those changes on branch patch_2_12_1.

**Comment by aaronhurst-google** [comment]
Sounds good.  Thanks Kevin!

**Comment by aaronhurst-google** [comment]
P.S. The branch has a typo: v12.2.1 instead of v2.12.1

**Comment by aaronhurst-google** [comment]
Your fix is cleaner, but you might want to verify the corner case `USD100.` (where there is a decimal point but no decimal digits). It's been a few weeks, but I recall testing this in a scratch org and finding that it was a valid currency literal.  That said, I can't imagine it's frequently used...

**Pull request merged**
